server:
  port: 8089

spring:
  datasource:
    password: 970816
    username: root
    url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: 172.75.200.148
#    port: 6379
#    password: